### ISSUE TITLE
Multi-sample option

### ISSUE THREAD

**Issue by YahGao** [xjtu-omics/SVision#10]
Hello.

We have generated several PacBio data. As I understand it, SVision calls SV for each sample. Can it process multiple samples together? My current idea is to call SV sample by sample and then merge them with SURVIVOR or Jasmine.

Thanks,
Yahui

**Comment by jiadong324** [comment]
Hi,

Thanks for your interest in our tool. 

You are correct. For cohort studies, you might need to detect sample by sample, and merge the results.

**Comment by YahGao** [comment]
Thanks for your reply
