### ISSUE TITLE
SV simulation issues

### ISSUE THREAD

**Issue by leedchou** [xjtu-omics/SVision#13]
Hi @jiadong324 ,

I am very interested in this work, and hopefully will be able to train a new model in terms of my own data sequened from other platforms with the help of this repository. 
I've read the supplementary information of **how to simulate SVs**, however, related scripts were not released in this repository. It stopped me from going forward any further as I have no idea on how you created SVs with the specific settings.
So much appreciation if you could share those scripts with me.

Thanks.

**Comment by songbowang125** [comment]
> Hi @jiadong324 ,
> 
> I am very interested in this work, and hopefully will be able to train a new model in terms of my own data sequened from other platforms with the help of this repository. I've read the supplementary information of **how to simulate SVs**, however, related scripts were not released in this repository. It stopped me from going forward any further as I have no idea on how you created SVs with the specific settings. So much appreciation if you could share those scripts with me.
> 
> Thanks.

We have just released those simulation scripts. Please check https://github.com/songbowang125/SVision-simulation for further usage.
