### ISSUE TITLE
Has it been tried in other diploid animals.

### ISSUE THREAD

**Issue by netwon123** [xjtu-omics/SVision#15]
Hi, I was wondering if this method has been tried in other diploid animals. In other species, complex structural variations are also important.###

**Comment by jiadong324** [comment]
We did not try on other diploid animals. In principle, SVision could be used directly on other specifies,  such as one of our users have applied SVision to sheep.

**Comment by jiadong324** [comment]
We did not try on other diploid animals. In principle, SVision could be used directly on other specifies,  such as one of our users have applied SVision to sheep.
