### ISSUE TITLE
ALT sequence for insertions

### ISSUE THREAD

**Issue by jo-mc** [xjtu-omics/SVision#16]
The VCF output for Insertions, ie ALT is currently <SV> do you plan on generating and putting the inserted sequence here?

**Comment by jiadong324** [comment]
Yes, we will add the insertion sequence. Note that this repository will soon merge to another method we are developing, which is able to detect both somatic and de novo SV and CSVs.

**Comment by jo-mc** [comment]
Thanks, our preliminary look at svision is very promising so will be looking out for the merged method.
