### ISSUE TITLE
can't install on mac

### ISSUE THREAD

**Issue by proukakis** [xjtu-omics/SVision#18]
hello
mac OS Monterey 12.6, Python 3.8.3
when i run the python setup.py install i get
No local packages or working download links found for tensorflow==1.14.0
error: Could not find suitable distribution for Requirement.parse('tensorflow==1.14.0')

I tried conda and brew install tensorflow, both seem to complete, still same error

thanks! Christos

**Comment by jiadong324** [comment]
Hi,

I have successfully installed on my Mac (V12.6.3 Monterey). The dependencies listed in the ```environment.yml``` contain ```tensorflow``` and other related packages. Please first run ```conda env create -f environment.yml``` to create a python 3.6 environment for further installation.

Please let me know if you have further issues.

**Comment by jiadong324** [comment]
Did you run ```conda env create -f environment.yml```? It seems that you are using ```pyenv``` to create the environment, which I have not tested yet.

**Comment by proukakis** [comment]
YEs i think the problem is tensor flow

error: Could not find suitable distribution for Requirement.parse('tensorflow==1.14.0')

we will give it a go on linux in a couple of weeks

thanks
