### ISSUE TITLE
Question about the result

### ISSUE THREAD

**Issue by kedduck** [xjtu-omics/SVision#19]
Thanks  for your software.

Recently I used SVision to detect sv. But I was confused when I  view result below:
 
```
H1_chr_01	3723331	611	N	<SV>	100	Covered	END=3723524;SVLEN=193;SVTYPE=INS;SUPPORT=1;BKPS=INS:192-3723202-3723208	GT:DR:DV ./.:1:1
H1_chr_01	3723331	611_1	N	<SV>	100	Covered	END=3723524;SVLEN=193;SVTYPE=DEL;SUPPORT=1;BKPS=DEL:195-3723460-3723655	GT:DR:DV ./.:1:1
```

The first line BKPS seems not correct "192-3723202-3723208"

These two lines have same Start and END, but BKPS is not same.

Could you  please help me?

Thanks!

**Comment by jiadong324** [comment]
Thanks for using our tool!

Based on your results, the same locus (pos at 3723331) is predicted two have different types of SVs. You could tell from the variant id ```611``` and ```611_1```. If you are calling from assemblies (```SUPPORT=1```), I guess this might be a heterogeneous locus containing INS and DEL. Note that it is not recommended to use ```SUPPORT=1``` event when detect from read alignments. 

Hope this help!

**Comment by kedduck** [comment]
Thanks for your reply!

You are right. The input was contigs.

I have a question about "BKPS", the second and others "BKPS" seems normal. Is the  first one correct?

**Comment by jiadong324** [comment]
I guess this insertion breakpoint is surrounded by tandem repeat. Could you please provide a screenshot of the alignment in IGV. This might be helpful.

**Comment by kedduck** [comment]
![image](https://github.com/xjtu-omics/SVision/assets/37659948/7a1f399e-b252-4ec2-8b77-dc77a7c7a8de)

![image](https://github.com/xjtu-omics/SVision/assets/37659948/8bd404a6-2306-4f48-9bea-5985c5bfac7d)
![image](https://github.com/xjtu-omics/SVision/assets/37659948/fcc7c0e7-c68f-4ba1-9749-0aab45549671)

```611_1``` starts at  3723460,but in VCF it starts with 3723331	

I not find ```611``` ...

**Comment by jiadong324** [comment]
The insertion might originated from the small gap in your first screenshot. There are some known issues of using SVision for assembly-based detection, as well as for the breakpoint. These will be optimized and pushed later.

**Comment by kedduck** [comment]
Thanks!
