### ISSUE TITLE
Can't run SVision with TypeError after installed from anaconda in Unbuntu

### ISSUE THREAD

**Issue by jackzhong1995** [xjtu-omics/SVision#28]
Hi, 

Thanks for the great tools SVision for calling complex SVs. 
I got an error after successfully installed SVision.My system is Ubuntu 20.04.4 
The error is ：
![image](https://github.com/xjtu-omics/SVision/assets/101613672/2d81b056-7942-46bb-9559-2a69aab8d203)

Is there any solution？
Best wishes.

**Comment by xuexingwangzhedishitian** [comment]
I think the emergence of SVision is exciting!

I met this error when running SVision, too. Do you solve this problem?
I have intalled the SVision software as the following. BUT the metaclass conflict happened when running SVision. When running the `start_up.py`, the partial dependencies is fail, I utilized `conda` install them. 

![image](https://github.com/xjtu-omics/SVision/assets/58718684/440c77f7-6623-476c-841e-b54d41b8b98b)

Best wishes.

**Comment by mhjiang97** [comment]
I also encountered this issue.
I reinstalled tensorflow using pip instead of conda, and now SVision is working perfectly.
Hope this is useful for you.
