### ISSUE TITLE
ERROR: No matching distribution found for pyvcf 0.6.8

### ISSUE THREAD

**Issue by wudikyy** [xjtu-omics/SVision#3]
hi，handsome and beauty:
When I executived command “conda env create -f ./environment.yml”, an error message is displayed “no matching distribution found for pyvcf = = 0.6.8”. I also try to install package pyvcf by executiving commond “pip install pyvcf = =0.6.8”, it still doesn’t work. How to fix this situation
![error](https://user-images.githubusercontent.com/31882756/177739692-876a09ad-6191-4a62-82db-bdea8c87be4e.jpg)
?

**Comment by songbowang125** [comment]
"PyVCF setup command: use_2to3 is invalid". This error is usually caused by high version of setuptools (since the parameter use_2to3=True was removed after setuptools v58). Re-install setuptools v57.5.0 (pip install setuptools==57.5.0) could solve this problem. Thanks~
