### ISSUE TITLE
save_restore_tensor.cc:175

### ISSUE THREAD

**Issue by asylvz** [xjtu-omics/SVision#35]
Hello, I'm trying to run SVision with default settings, but I get the following error. I checked the md5sum of the cnn model and I there seems to be no such problem.  Any idea?

SVision -o res/ -b bam_file.bam -m svision-cnn-model.ckpt.data-00000-of-00001 -g 1KG_ONT_VIENNA_hg38.fa -n ${sample} -t 24

Error message:
[SVision_error.txt](https://github.com/user-attachments/files/16863442/SVision_error.txt)

**Comment by paudano** [comment]
Try running it without specifying “.data-00000-of-00001” on the model filename.
 
We’ve run it with “-m $SVISION_MODEL_PATH/svision-cnn-model.ckpt”
 
Here’s a post where someone had the same issue:
https://stackoverflow.com/questions/48438122/import-meta-graph-fails-with-data-loss-not-an-sstable-bad-magic-number

**Comment by jiadong324** [comment]
Thanks Peter @paudano for your response. 

@asylvz Just suggested by Peter, please use the model as ```svision-cnn-model.ckpt``` without the suffix. Please let me know if you have any questions.

**Comment by asylvz** [comment]
It worked perfectly after changing the filename.

Thanks a lot @paudano and @jiadong324.
