### ISSUE TITLE
是否适合非模式物种的SV检测？

### ISSUE THREAD

**Issue by biozzq** [xjtu-omics/SVision#6]
您好，

我研究的物种有31条常染色体，通过下面的命令，我发现结果只报告到24号染色体。是不是有其它参数可以调整，非常感谢。

`SVision -o svision_NQ -b NQ.sorted.bam --min_gt_depth 1 --contig -s 1 -m /model/svision-cnn-model.ckpt -g toplevel.fa -n NQ --graph --qname`

祝好
郑竹清

**Comment by biozzq** [comment]
@jiadong324 

Thank you, the species I focussed on is horse. I will try the new version after you have added this species.

Best,
Zheng zhuqing

**Comment by jiadong324** [comment]
@biozzq The new version is released, please try and see what's going on.
