### ISSUE TITLE
Unknown INFO field: VAF when add --cluster

### ISSUE THREAD

**Issue by rxw125** [xjtu-omics/SVision#7]
hi,all
       when I  run Svision with --cluster, it would fail and raise errors at step2 CNN prediction.
       The last info in log is  :
       2022-10-06 14:35:17,688 [INFO   ]  [Additional Func: cluster] Starting cluster original callset......
       Errors are as follows:
> Traceback (most recent call last):
  File /opt/install/Anaconda3/envs/svisionenvnew/bin/SVision", line 4, in <module>
    __import__('pkg_resources').run_script('SVision==1.3.7', 'SVision')
  File /opt/install/Anaconda3/envs/svisionenvnew/lib/python3.6/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File /opt/install/Anaconda3/envs/svisionenvnew/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File /opt/install/Anaconda3/envs/svisionenvnew/lib/python3.6/site-packages/SVision-1.3.7-py3.6.egg/EGG-INFO/scripts/SVision", line 457, in <module>
    cluster_original_callset(merged_vcf_path, work_dir, sample_path, cluster_out_file)
  File /opt/install/Anaconda3/envs/svisionenvnew/lib/python3.6/site-packages/SVision-1.3.7-py3.6.egg/src/network/output.py", line 184, in cluster_original_callset
    vaf = record.info['VAF']
  File "pysam/libcbcf.pyx", line 2563, in pysam.libcbcf.VariantRecordInfo.__getitem__
KeyError: 'Unknown INFO field: VAF'

     There is not tag VAF  in vcf produced without "--cluster"  parameter, so I think this mybe a bug or something else.

**Comment by jiadong324** [comment]
Thanks for your interest in our tool.

I noticed that you are using V1.3.7. The ```--cluster``` aims to capture large complex events (e.g. chromothripsis) and it is  underdevelopment. The ```--cluster``` option is no longer available in the latest version (V1.3.8).

**Comment by rxw125** [comment]
Thank you for your reply
